# Generated by Django 4.1 on 2022-11-17 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shop_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('debt', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=50)),
                ('income_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('total', models.PositiveSmallIntegerField()),
                ('payed', models.PositiveSmallIntegerField()),
                ('debt', models.PositiveSmallIntegerField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
                ('salesman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.warehouse'),
        ),
        migrations.AddField(
            model_name='client',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.warehouse'),
        ),
    ]
