# Generated by Django 4.1 on 2022-11-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_salesman_client_warehouse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='title',
            new_name='shop',
        ),
    ]
