# Generated by Django 4.1 on 2022-11-17 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rename_title_warehouse_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='user',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
